=== Rose2161/casper-account-info-standard/schema.json
{
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "title": "Casper Account Information Standard",
    "description": "Information about an Account on the Casper Network",
    "type": "object",
    "$defs": {
        "location": {
            "type": "object",
            "required": [
                "name",
                "country"
            ],
            "properties": {
                "name": {
                    "description": "Location in human readable format [City, State]",
                    "type": "string",
                    "minLength": 3
                },
                "country": {
                    "description": "ISO 3166-1 alpha 2 country code [XX]",
                    "type": "string",
                    "maxLength": 2,
                    "minLength": 2,
                    "pattern": "^[A-Z]+$"
                },
                "latitude": {
                    "description": "Latitude in decimal degrees",
                    "type": "number"
                },
                "longitude": {
                    "description": "Longitude in decimal degrees",
                    "type": "number"
                }
            }
        },
        "required_url": {
            "type": "string",
            "format": "uri",
            "pattern": "^https?://.+[^\/]$"
        },
        "optional_url": {
            "type": "string",
            "if": {
                "pattern": ".+"
            },
            "then": {
                "format": "uri",
                "pattern": "^https?://.+[^\/]$"
            }
        },
        "username": {
            "type": "string",
            "pattern": "^[\\w\\d_\\-.]*$"
        },
        "facebook_username": {
            "type": "string",
            "pattern": "^[\\w\\d_\\-./]*$"
        },
        "youtube_username": {
            "type": "string",
            "pattern": "^[\\w\\d_\\-./]*$"
        },
        "casper_public_key": {
            "type": "string",
            "maxLength": 68,
            "minLength": 66,
            "pattern": "^[a-fA-F0-9]{66,68}$"
        }
    },
    "required": [
        "owner",
        "owner_name",
        "owner_type"
    ],
    "additionalProperties": false,
    "properties": {
        "owner_name": {
            "$id": "#/properties/owner_name",
            "type": "string",
            "description": "The name of the entity or person that owns the Account",
            "maxLength": 32,
            "minLength": 3
        },
        "owner_description": {
            "$id": "#/properties/owner_description",
            "type": "string",
            "description": "An optional description of the Owner of the Account",
            "maxLength": 200
        },
        "owner_type": {
            "$id": "#/properties/owner_type",
            "type": "array",
            "description": "Indicates the type of entity of the owner. One Owner can have multiple types.",
            "uniqueItems": true,
            "minItems": 1,
            "items": {
                "$id": "#/properties/owner_type/items",
                "type": "string",
                "enum": [
                    "validator",
                    "exchange",
                    "dapp",
                    "individual",
                    "corporation",
                    "dao"
                ]
            }
        },
        "owner": {
            "$id": "#/properties/owner",
            "type": "object",
            "description": "More detailed information about the Owner of the Account",
            "required": [
                "identity"
            ],
            "properties": {
                "identity": {
                    "$id": "#/properties/owner/properties/identity",
                    "type": "object",
                    "description": "Information about the ownership of the Account.",
                    "required": [],
                    "properties": {
                        "ownership_disclosure": {
                            "$id": "#/properties/owner/properties/identity/properties/ownership_disclosure",
                            "$ref": "#/$defs/optional_url",
                            "description": "Link to a page outlining entity ownership and/or governance"
                        },
                        "casper_association_kyc_web": {
                            "$id": "#/properties/owner/properties/identity/properties/casper_association_kyc_web",
                            "$ref": "#/$defs/optional_url",
                            "description": "Reserved for a link to a Casper Association provided verified identity document, as applicable to Validator members of the Association"
                        },
                        "casper_association_kyc_onchain": {
                            "$id": "#/properties/owner/properties/identity/properties/casper_association_kyc_onchain",
                            "type": "string",
                            "description": "Reserved for Casper Associated on-chain resource that provides for a verified identity"
                        }
                    },
                    "additionalProperties": false
                },
                "resources": {
                    "$id": "#/properties/owner/properties/resources",
                    "type": "object",
                    "description": "Additional online resources provided by the Account owner",
                    "required": [],
                    "properties": {
                        "code_of_conduct": {
                            "$id": "#/properties/owner/properties/resources/properties/code_of_conduct",
                            "$ref": "#/$defs/optional_url",
                            "description": "A link to a Code of Conduct document"
                        },
                        "terms_of_service": {
                            "$id": "#/properties/owner/properties/resources/properties/terms_of_service",
                            "$ref": "#/$defs/optional_url",
                            "description": "A link to the Terms of Service applicable to the use of Owner's services, such as network validation and staking"
                        },
                        "privacy_policy": {
                            "$id": "#/properties/owner/properties/resources/properties/privacy_policy",
                            "$ref": "#/$defs/optional_url",
                            "description": "A link to a Privacy Policy, as may be applicable to personal information provided to the Account Owner"
                        },
                        "other": {
                            "$id": "#/properties/owner/properties/resources/properties/other",
                            "type": "array",
                            "uniqueItems": true,
                            "description": "Links to other relevant resources",
                            "items": {
                                "$id": "#/properties/owner/properties/resources/properties/other/items",
                                "$ref": "#/$defs/optional_url"
                            }
                        }
                    },
                    "additionalProperties": false
                },
                "associated_accounts": {
                    "$id": "#/properties/owner/properties/associated_accounts",
                    "type": "array",
                    "description": "A list of additional accounts owned by the same owner. Declaring additional accounts provides transparency with respect to Exchange-owned wallets, or self-staked funds belonging to Validators. In order for an associated account o be considered valid, it needs to register the same base URL with the Casper Account Info Standard contract as the Owner",
                    "additionalItems": false,
                    "items": {
                        "$id": "#/properties/owner/properties/associated_accounts/items",
                        "$ref": "#/$defs/casper_public_key"
                    }
                },
                "website": {
                    "$id": "#/properties/owner/properties/website",
                    "$ref": "#/$defs/required_url",
                    "description": "A link to the Owner's website"
                },
                "email": {
                    "$id": "#/properties/owner/properties/email",
                    "format": "email",
                    "type": "string",
                    "description": "E-mail address for the Owner"
                },
                "branding": {
                    "$id": "#/properties/owner/properties/branding",
                    "type": "object",
                    "description": "Graphical assets to visually identify the Owner",
                    "required": [
                        "logo_256"
                    ],
                    "properties": {
                        "logo_256": {
                            "$id": "#/properties/owner/properties/branding/properties/logo_256",
                            "$ref": "#/$defs/required_url",
                            "description": "Link to Owner logo [PNG format, 256x256]"
                        },
                        "logo_1024": {
                            "$id": "#/properties/owner/properties/branding/properties/logo_1024",
                            "$ref": "#/$defs/optional_url",
                            "description": "Link to Owner logo [PNG format, 1024x1024]"
                        },
                        "logo_svg": {
                            "$id": "#/properties/owner/properties/branding/properties/logo_svg",
                            "$ref": "#/$defs/optional_url",
                            "description": "Link to Owner logo [SVG format]"
                        }
                    },
                    "additionalProperties": false
                },
                "location": {
                    "$id": "#/properties/owner/properties/location",
                    "$ref": "#/$defs/location",
                    "description": "The location of the Owner of the Account"
                },
                "social": {
                    "$id": "#/properties/owner/properties/social",
                    "type": "object",
                    "description": "Links to the Owner's social media profiles",
                    "required": [],
                    "properties": {
                        "keybase": {
                            "$id": "#/properties/owner/properties/social/properties/keybase",
                            "$ref": "#/$defs/username",
                            "description": "username only"
                        },
                        "telegram": {
                            "$id": "#/properties/owner/properties/social/properties/telegram",
                            "$ref": "#/$defs/username",
                            "description": "username only"
                        },
                        "twitter": {
                            "$id": "#/properties/owner/properties/social/properties/twitter",
                            "$ref": "#/$defs/username",
                            "description": "username only"
                        },
                        "github": {
                            "$id": "#/properties/owner/properties/social/properties/github",
                            "$ref": "#/$defs/username",
                            "description": "username only"
                        },
                        "youtube": {
                            "$id": "#/properties/owner/properties/social/properties/youtube",
                            "$ref": "#/$defs/youtube_username",
                            "description": "channel address only"
                        },
                        "facebook": {
                            "$id": "#/properties/owner/properties/social/properties/facebook",
                            "$ref": "#/$defs/facebook_username",
                            "description": "Facebook Page or Facebook Group address only, not the full URL"
                        },
                        "medium": {
                            "$id": "#/properties/owner/properties/social/properties/medium",
                            "$ref": "#/$defs/username",
                            "description": "username only"
                        },
                        "reddit": {
                            "$id": "#/properties/owner/properties/social/properties/reddit",
                            "$ref": "#/$defs/username",
                            "description": "username only"
                        },
                        "wechat": {
                            "$id": "#/properties/owner/properties/social/properties/wechat",
                            "$ref": "#/$defs/username",
                            "description": "username only"
                        }
                    },
                    "additionalProperties": false
                }
            },
            "additionalProperties": false
        },
        "nodes": {
            "$id": "#/properties/nodes",
            "type": "array",
            "description": "List of nodes operated by the Account Owner",
            "additionalItems": false,
            "items": {
                "$id": "#/properties/nodes/items",
                "type": "object",
                "required": [
                    "node_account_address"
                ],
                "properties": {
                    "node_account_address": {
                        "$id": "#/properties/nodes/items/properties/node_description",
                        "$ref": "#/$defs/casper_public_key"
                    },
                    "node_description": {
                        "$id": "#/properties/nodes/items/properties/node_description",
                        "type": "string",
                        "description": "A description of the use and functionality of this node"
                    },
                    "location": {
                        "$id": "#/properties/nodes/items/properties/location",
                        "$ref": "#/$defs/location",
                        "description": "The location of this node."
                    },
                    "features": {
                        "$id": "#/properties/nodes/items/properties/features",
                        "type": "array",
                        "description": "Reserved to describe the features provided by this node",
                        "additionalItems": false,
                        "uniqueItems": true,
                        "minItems": 1,
                        "items": {
                            "$id": "#/properties/nodes/items/properties/features/items",
                            "type": "string",
                            "enum": [
                                "validator",
                                "rpc-proxy",
                                "sse-proxy",
                                "read-only",
                                "other"
                            ]
                        }
                    }
                }
            }
        }
    }
}

=== Rose2161/casper-account-info-standard/account-info.json
{
    "owner_name": "",
    "owner_description": "",
    "owner_type": [],
    "owner": {
        "identity": {
            "ownership_disclosure": "",
            "casper_association_kyc_web": "",
            "casper_association_kyc_onchain": ""
        },
        "resources": {
            "code_of_conduct": "",
            "terms_of_service": "",
            "privacy_policy": "",
            "other": []
        },
        "associated_accounts": [],
        "website": "",
        "email": "",
        "branding": {
            "logo_256": "",
            "logo_1024": "",
            "logo_svg": ""
        },
        "location": {
            "name": "",
            "country": "",
            "latitude": 0,
            "longitude": 0
        },
        "social": {
            "keybase": "",
            "telegram": "",
            "twitter": "",
            "github": "",
            "youtube": "",
            "facebook": "",
            "medium": "",
            "reddit": "",
            "wechat": ""
        }
    },
    "nodes": [
        {
            "node_account_address": "",
            "node_description": "",
            "location": {
                "name": "",
                "country": "",
                "latitude": 0,
                "longitude": 0
            },
            "features": []
        }
    ]
}
